# Generated by Django 4.2.2 on 2023-11-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_store', '0002_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='wikipedia_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
