# Generated by Django 4.2.2 on 2023-11-17 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_store', '0003_department_wikipedia_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='dept_name',
            new_name='department_name',
        ),
    ]
